# Generated by Django 4.0.1 on 2022-02-08 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catigory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('job_type', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=20)),
                ('description', models.TextField(default='', max_length=100)),
                ('published_at', models.DateField(auto_now=True)),
                ('vacancy', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('image', models.ImageField(upload_to='jobs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catigory.catigory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
