# Generated by Django 4.0.1 on 2022-02-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='job',
        ),
    ]
